[package]
name = "token_wallet_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.6"
ic-cdk-macros = "0.6"
candid = "0.7"
serde = { version = "1.0", features = ["derive"] }
